# Generated by Django 5.2.7 on 2025-10-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0006_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_time',
            field=models.CharField(default='10:00 AM - 5:00 PM', max_length=100),
        ),
    ]
